repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: sync-requirements
        name: Sync Requirements
        entry: ./generate_requirements.sh
        language: system
        pass_filenames: false
        description: Ensures requirements.txt is in sync with uv.lock before commit.
        always_run: true