#!/bin/bash
# generate_requirements.sh - Keeps requirements.txt in sync with uv.lock

set -e # Exit immediately if a command exits with a non-zero status.

echo "🔄 Syncing dependencies and updating lockfile..."
uv lock

echo "📦 Exporting dependencies to requirements.txt..."
# --no-dev: Excludes development dependencies
# --no-hashes: Removes package hashes
# --no-annotate: Removes the "# via ..." comments for a much cleaner file
# --no-header: Removes the autogenerated comment at the top
uv export --format requirements-txt --output-file requirements.txt --no-dev --no-hashes --no-annotate --no-header

echo "🔌 Injecting extra index for PyTorch CPU..."
# Extract the extra index URL from pyproject.toml
EXTRA_INDEX_URL=$(grep -A 5 '\[\[tool.uv.index\]\]' pyproject.toml | grep "url =" | head -n 1 | cut -d '"' -f 2)
if [ -n "$EXTRA_INDEX_URL" ] && ! grep -q "$EXTRA_INDEX_URL" requirements.txt; then
    sed -i "1i --extra-index-url $EXTRA_INDEX_URL" requirements.txt
fi

echo "🔍 Extracting metadata..."
# Extract versions dynamically from lock and config files for accuracy
GRADIO_VERSION=$(grep -A 1 'name = "gradio"' uv.lock | grep "version =" | head -n 1 | cut -d '"' -f 2)
PYTHON_VERSION=$(grep "requires-python =" pyproject.toml | cut -d '"' -f 2 | tr -d '>= ')

echo "📍 Gradio version: $GRADIO_VERSION"
echo "📍 Python version: $PYTHON_VERSION"

sed -i "s/^sdk_version: .*/sdk_version: \"$GRADIO_VERSION\"/" README.md
sed -i "s/^python_version: .*/python_version: \"$PYTHON_VERSION\"/" README.md

echo "✅ requirements.txt has been successfully updated."
echo "💡 Note: This file is used for HuggingFace Space deployment."
